@url=http://localhost:3005
@cookie=refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2E5YzNhMjc1OGMxYzJmNGU3OGQ1OCIsInJvbGUiOiJpbmFjdGl2YXRlZCIsImlhdCI6MTcxOTMxMTQyMiwiZXhwIjoxNzIwMTc1NDIyfQ.JyXZ-KR7_RtvbKIS_cxSrRM8Nciz28LrB6t5q8Vq_7g
get {{url}}/auth/refresh
Cookie: {{cookie}}
