@url=http://localhost:3005/api/user
@json=Content-Type: application/json
@cookie=sessionId=abc123

### 测试路由
get {{url}}/register/email
### 所有用户
get {{url}}/users
### 删除所有用户
delete {{url}}/delete-user

### 检查email
patch {{url}}/register/email
{{json}}

{
    "email": "soteric.test2@gmail.com"
}


### 检查username
post {{url}}/register/email
{{json}}

{
    "username": "dean_liu"
}

### 注册preRegister "esoteric.test2@gmail.com"
put {{url}}/register/email
{{json}}

{
    "email": "esoteric.test2@gmail.com",
    "password": "E_dean_x1.1",
    "username": "dean_liu"
}

### 登陆
post {{url}}/login

